### ISSUE TITLE
Possible bug in MPI_Type_create_struct on i386/i686

### ISSUE THREAD

**Issue by dalcinl** [pmodels/mpich#5684]
This is a follow up of mpi4py/mpi4py#105.

I believe there is a bug on `MPI_Type_create_struct` for a C struct with the following layout `struct s {char a; long double b; char c;};` (on i386, `long double` has size 12 but alignment is 4, so `sizeof(struct s)` is 20). Creating a corresponding MPI struct datatype, you get a datatype with different extent than `sizeof(struct s)`.

I tried my struct example above on a Debian 11 i686 with apt MPICH (running on a VM with Gnome Boxes). Unfortunately, right now I'm on vacation and I cannot access my home workstation were I performed the test.

@drew-parsons Maybe you can assist us with this one?

**Comment by hzhou** [comment]
Thanks @dalcinl for posting the ticket. I was setting up 32-bit CI for mpi4py and got interrupted (due to need a step from system to set up 32-bit CI for `mpi4py`). We'll follow up.

**Comment by drew-parsons** [comment]
For me the symptom shows up in the mpi4py tests,
```
testStruct3 (test_util_dtlib.TestUtilDTLib) ... ok
testStruct4 (test_util_dtlib.TestUtilDTLib) ... 
======================================================================
FAIL: testStruct4 (test_util_dtlib.TestUtilDTLib) (typecode='g')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dparsons/mpi4py/mpi4py-3.1.1/test/test_util_dtlib.py", line 172, in testStruct4
    self.assertEqual(mt.extent, n*ex1)
AssertionError: 24 != 20
```
Let me know if there's any code tests or patches you'd like me to run.

**Comment by hzhou** [comment]
We ran the mpi4py tests on 32-bit linux. With ch3, we get:
```
testStruct4 (test_util_dtlib.TestUtilDTLib) ... skipped 'numpy'
```
I guess we need install numpy for that test?

With ch4, it is interrupted by an assertion:
```
testCreateContiguous (test_datatype.TestDatatype) ... python3.6: src/mpi/datatype/typerep/src/typerep_yaksa_init.c:299: MPII_Typerep_get_yaksa_type: Assertion `0' failed.
python3.6: src/mpi/datatype/typerep/src/typerep_yaksa_init.c:299: MPII_Typerep_get_yaksa_type: Assertion `0' failed.
python3.6: src/mpi/datatype/typerep/src/typerep_yaksa_init.c:299: MPII_Typerep_get_yaksa_type: Assertion `0' failed.
python3.6: src/mpi/datatype/typerep/src/typerep_yaksa_init.c:299: MPII_Typerep_get_yaksa_type: Assertion `0' failed.
```
This is being addressed in https://github.com/pmodels/mpich/pull/5686.

We'll check it again once we resolve them.

**Comment by dalcinl** [comment]
> I guess we need install numpy for that test?

Yes, please. Installing NumPy will enable more tests. If you are using system Python, just use the system pkg manager to install numpy.

**Comment by hzhou** [comment]
I tested under ubuntu-18.04-i386 under `qemu`, need manually install `cython` to build `mpi4py`. With `ch3`, got this error:
```
testPackUnpackExternal (test_pack.TestPackExternal) ... Conversion of types whose size is not the same as the size in external32 is not supported
Aborting with internal error
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
```
But after skipping this test, the rest of the tests all passed, including `testStruct4`.

**Comment by dalcinl** [comment]
> I tested under ubuntu-18.04-i386 under `qemu`

I ran my tests on Debian 11 i686 (VM in Gnome Boxes). Perhaps different MPICH version? Reminder: I used system MPICH installed with `apt`. Did you install NumPy?

In any case, there is no need to install mpi4py to test for the issue. Just create a struct datatype corresponding to `struct s {char a; long double b; char c;}`, and check that the datatype extent matches `sizeof(struct s)`.

**Comment by hzhou** [comment]
Looks like both current main branch is fine with both `ch3` and `ch4`. I'll check at which point we fixed it.

**Comment by dalcinl** [comment]
Perhaps it was #5144?

**Comment by hzhou** [comment]
> 

Plausible. Treating alignment the same as type size will certainly fail the test you mentioned.

**Comment by dalcinl** [comment]
> `AssertionError: 24 != 20`

And that would explain the datatype extent being `24`.

@drew-parsons Looks like the issue is already fixed in `mpich/master`. Any chance you could try MPICH from a git checkout? Right now I do not have convenient access to my hardware and VMs at home.

**Comment by hzhou** [comment]
> > `AssertionError: 24 != 20`
> 
> And that would explain the datatype extent being `24`.
> 
> @drew-parsons Looks like the issue is already fixed in `mpich/master`. Any chance you could try MPICH from a git checkout? Right now I do not have convenient access to my hardware and VMs at home.

FYI we have released mpich `4.0b1` https://www.mpich.org/downloads/

**Comment by drew-parsons** [comment]
Thanks guys. Will need some days to get on to it, but will test the patch or new release.

**Comment by drew-parsons** [comment]
I've now built mpi4py 3.1.3 against mpich 4.0.1.  Looks like the patch has fixed dtlib for mpich:
```
~/mpich/mpi4py-3.1.3/test$ PYTHONPATH=~/mpich/mpi4py-3.1.3/debian/python3-mpi4py/usr/lib/python3/dist-packages/:$PYTHONPATH mpirun.mpich -n 5 python3 -m pytest -v test_util_dtlib.py
============================= test session starts ==============================
platform linux -- Python 3.9.11, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/dparsons/mpich/mpi4py-3.1.3, configfile: setup.cfg
collecting ... ============================= test session starts ==============================
platform linux -- Python 3.9.11, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/dparsons/mpich/mpi4py-3.1.3, configfile: setup.cfg
collecting ... ============================= test session starts ==============================
platform linux -- Python 3.9.11, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/dparsons/mpich/mpi4py-3.1.3, configfile: setup.cfg
collecting ... ============================= test session starts ==============================
platform linux -- Python 3.9.11, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/dparsons/mpich/mpi4py-3.1.3, configfile: setup.cfg
collecting ... ============================= test session starts ==============================
platform linux -- Python 3.9.11, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/dparsons/mpich/mpi4py-3.1.3, configfile: setup.cfg
collecting ... collected 19 items

test_util_dtlib.py::TestUtilDTLib::testAlignment PASSED                  [  5%]
test_util_dtlib.py::TestUtilDTLib::testBasic PASSED                      [ 10%]
test_util_dtlib.py::TestUtilDTLib::testCoverage PASSED                   [ 15%]
test_util_dtlib.py::TestUtilDTLib::testF77 PASSED                        [ 21%]
test_util_dtlib.py::TestUtilDTLib::testF90 PASSED                        [ 26%]
test_util_dtlib.py::TestUtilDTLib::testF90Complex PASSED                 [ 31%]collected 19 items

test_util_dtlib.py::TestUtilDTLib::testAlignment 
test_util_dtlib.py::TestUtilDTLib::testF90Integer PASSED                  [  5%]PASSED                 [ 36%]
test_util_dtlib.py::TestUtilDTLib::testF90Real PASSED                    [ 42%]
test_util_dtlib.py::TestUtilDTLib::testBasic 
test_util_dtlib.py::TestUtilDTLib::testFailures PASSED                   [ 47%]
test_util_dtlib.py::TestUtilDTLib::testHIndexed PASSED                      [ 10%]collected 19 items

test_util_dtlib.py::TestUtilDTLib::testAlignment 
test_util_dtlib.py::TestUtilDTLib::testCoverage PASSED                   [ 15%]
test_util_dtlib.py::TestUtilDTLib::testF77 PASSED                        [ 21%]PASSED                  [  5%]
test_util_dtlib.py::TestUtilDTLib::testF90 PASSED                        [ 26%]
test_util_dtlib.py::TestUtilDTLib::testF90Complex 
test_util_dtlib.py::TestUtilDTLib::testBasic PASSED                 [ 31%]PASSED                      [ 10%]
test_util_dtlib.py::TestUtilDTLib::testF90Integer PASSED                 [ 36%]
test_util_dtlib.py::TestUtilDTLib::testCoverage PASSED                   [ 15%]
test_util_dtlib.py::TestUtilDTLib::testF77 PASSED                        [ 21%]
test_util_dtlib.py::TestUtilDTLib::testF90 PASSED                        [ 26%]collected 19 items

test_util_dtlib.py::TestUtilDTLib::testAlignment 
test_util_dtlib.py::TestUtilDTLib::testF90Real PASSED                    [ 42%]PASSED                  [  5%]collected 19 items

test_util_dtlib.py::TestUtilDTLib::testAlignment 
test_util_dtlib.py::TestUtilDTLib::testBasic 
test_util_dtlib.py::TestUtilDTLib::testF90Complex PASSED                 [ 31%]PASSED                  [  5%]PASSED                      [ 10%]
test_util_dtlib.py::TestUtilDTLib::testBasic 
test_util_dtlib.py::TestUtilDTLib::testCoverage 
test_util_dtlib.py::TestUtilDTLib::testF90Integer 
test_util_dtlib.py::TestUtilDTLib::testFailures PASSED                   [ 15%]
test_util_dtlib.py::TestUtilDTLib::testF77 PASSED                   [ 47%]PASSED                        [ 21%]PASSED                      [ 10%]
test_util_dtlib.py::TestUtilDTLib::testF90 
test_util_dtlib.py::TestUtilDTLib::testCoverage PASSED                        [ 26%]PASSED                   [ 15%]
test_util_dtlib.py::TestUtilDTLib::testF90Complex 
test_util_dtlib.py::TestUtilDTLib::testF77 
test_util_dtlib.py::TestUtilDTLib::testHIndexed PASSED                        [ 21%]PASSED                 [ 31%]
test_util_dtlib.py::TestUtilDTLib::testF90Integer 
test_util_dtlib.py::TestUtilDTLib::testF90 PASSED                        [ 26%]
test_util_dtlib.py::TestUtilDTLib::testF90Complex PASSED                 [ 31%]
test_util_dtlib.py::TestUtilDTLib::testF90Integer PASSED                 [ 36%]
test_util_dtlib.py::TestUtilDTLib::testF90Real PASSED                   [ 52%]
test_util_dtlib.py::TestUtilDTLib::testHVector PASSED                    [ 42%]
test_util_dtlib.py::TestUtilDTLib::testFailures PASSED                 [ 36%]
test_util_dtlib.py::TestUtilDTLib::testF90Real PASSED                   [ 47%]
test_util_dtlib.py::TestUtilDTLib::testHIndexed PASSED                    [ 42%]PASSED                 [ 36%]
test_util_dtlib.py::TestUtilDTLib::testFailures 
test_util_dtlib.py::TestUtilDTLib::testF90Real PASSED                   [ 47%]
test_util_dtlib.py::TestUtilDTLib::testHIndexed PASSED                    [ 42%]
test_util_dtlib.py::TestUtilDTLib::testFailures PASSED                   [ 47%]
test_util_dtlib.py::TestUtilDTLib::testHIndexed PASSED                   [ 52%]
test_util_dtlib.py::TestUtilDTLib::testHVector PASSED                   [ 52%]PASSED                   [ 52%]
test_util_dtlib.py::TestUtilDTLib::testHVector 
test_util_dtlib.py::TestUtilDTLib::testHVector PASSED                    [ 57%]
test_util_dtlib.py::TestUtilDTLib::testIndexed PASSED                   [ 52%]
test_util_dtlib.py::TestUtilDTLib::testHVector PASSED                    [ 57%]
test_util_dtlib.py::TestUtilDTLib::testIndexed PASSED                    [ 57%]
test_util_dtlib.py::TestUtilDTLib::testIndexed PASSED                    [ 63%]
test_util_dtlib.py::TestUtilDTLib::testStruct1 PASSED                    [ 63%]
test_util_dtlib.py::TestUtilDTLib::testStruct1 PASSED                    [ 57%]
test_util_dtlib.py::TestUtilDTLib::testIndexed PASSED                    [ 57%]PASSED                    [ 63%]
test_util_dtlib.py::TestUtilDTLib::testStruct1 
test_util_dtlib.py::TestUtilDTLib::testIndexed PASSED                    [ 63%]
test_util_dtlib.py::TestUtilDTLib::testStruct1 PASSED                    [ 63%]
test_util_dtlib.py::TestUtilDTLib::testStruct1 PASSED                    [ 68%]
test_util_dtlib.py::TestUtilDTLib::testStruct2 PASSED                    [ 68%]
test_util_dtlib.py::TestUtilDTLib::testStruct2 PASSED                    [ 68%]
test_util_dtlib.py::TestUtilDTLib::testStruct2 PASSED                    [ 68%]
test_util_dtlib.py::TestUtilDTLib::testStruct2 PASSED                    [ 68%]
test_util_dtlib.py::TestUtilDTLib::testStruct2 PASSED                    [ 73%]
test_util_dtlib.py::TestUtilDTLib::testStruct3 PASSED                    [ 78%]
test_util_dtlib.py::TestUtilDTLib::testStruct4 PASSED                    [ 73%]
test_util_dtlib.py::TestUtilDTLib::testStruct3 PASSED                    [ 78%]
test_util_dtlib.py::TestUtilDTLib::testStruct4 PASSED                    [ 84%]
test_util_dtlib.py::TestUtilDTLib::testSubarray1 PASSED                  [ 89%]
test_util_dtlib.py::TestUtilDTLib::testSubarray2 PASSED                  [ 94%]
test_util_dtlib.py::TestUtilDTLib::testVector PASSED                    [ 84%]
test_util_dtlib.py::TestUtilDTLib::testSubarray1 PASSED                  [ 89%]
test_util_dtlib.py::TestUtilDTLib::testSubarray2 PASSED                  [ 94%]
test_util_dtlib.py::TestUtilDTLib::testVector PASSED                     [100%]

============================= 19 passed in 14.08s ==============================
PASSED                     [100%]

============================= 19 passed in 14.18s ==============================
PASSED                    [ 73%]
test_util_dtlib.py::TestUtilDTLib::testStruct3 PASSED                    [ 78%]
test_util_dtlib.py::TestUtilDTLib::testStruct4 PASSED                    [ 84%]
test_util_dtlib.py::TestUtilDTLib::testSubarray1 PASSED                  [ 89%]
test_util_dtlib.py::TestUtilDTLib::testSubarray2 PASSED                  [ 94%]
test_util_dtlib.py::TestUtilDTLib::testVector PASSED                     [100%]

============================= 19 passed in 14.37s ==============================
PASSED                    [ 73%]
test_util_dtlib.py::TestUtilDTLib::testStruct3 PASSED                    [ 78%]
test_util_dtlib.py::TestUtilDTLib::testStruct4 PASSED                    [ 84%]
test_util_dtlib.py::TestUtilDTLib::testSubarray1 PASSED                  [ 89%]
test_util_dtlib.py::TestUtilDTLib::testSubarray2 PASSED                  [ 94%]
test_util_dtlib.py::TestUtilDTLib::testVector PASSED                    [ 73%]
test_util_dtlib.py::TestUtilDTLib::testStruct3 PASSED                    [ 78%]
test_util_dtlib.py::TestUtilDTLib::testStruct4 PASSED                     [100%]

============================= 19 passed in 14.54s ==============================
PASSED                    [ 84%]
test_util_dtlib.py::TestUtilDTLib::testSubarray1 PASSED                  [ 89%]
test_util_dtlib.py::TestUtilDTLib::testSubarray2 PASSED                  [ 94%]
test_util_dtlib.py::TestUtilDTLib::testVector PASSED                     [100%]

============================= 19 passed in 14.77s ==============================
```

**Comment by hzhou** [comment]
Sounds good. I am closing the issue.

**Comment by drew-parsons** [comment]
p.s. in case someone asks, here is the TestIOSelf record (passing) of the test log with mpich on i386.  It's still failing with openmpi (https://github.com/mpi4py/mpi4py/issues/105).
```
...
testPyMethods (test_info.TestInfoEnv) ... ok
testTruth (test_info.TestInfoEnv) ... ok
testPyMethods (test_info.TestInfoNull) ... ok
testTruth (test_info.TestInfoNull) ... ok
testIReadIWrite (test_io.TestIOSelf) ... ok
testIReadIWriteAll (test_io.TestIOSelf) ... ok
testIReadIWriteAt (test_io.TestIOSelf) ... ok
testIReadIWriteAtAll (test_io.TestIOSelf) ... ok
testIReadIWriteShared (test_io.TestIOSelf) ... ok
testReadWrite (test_io.TestIOSelf) ... ok
testReadWriteAll (test_io.TestIOSelf) ... ok
testReadWriteAllBeginEnd (test_io.TestIOSelf) ... ok
testReadWriteAt (test_io.TestIOSelf) ... ok
testReadWriteAtAll (test_io.TestIOSelf) ... ok
testReadWriteAtAllBeginEnd (test_io.TestIOSelf) ... ok
testReadWriteOrdered (test_io.TestIOSelf) ... ok
testReadWriteOrderedBeginEnd (test_io.TestIOSelf) ... ok
testReadWriteShared (test_io.TestIOSelf) ... ok
testIReadIWrite (test_io.TestIOWorld) ... ok
testIReadIWriteAll (test_io.TestIOWorld) ... ok
testIReadIWriteAt (test_io.TestIOWorld) ... ok
testIReadIWriteAtAll (test_io.TestIOWorld) ... ok
testIReadIWriteShared (test_io.TestIOWorld) ... ok
testReadWrite (test_io.TestIOWorld) ... ok
testReadWriteAll (test_io.TestIOWorld) ... ok
testReadWriteAllBeginEnd (test_io.TestIOWorld) ... ok
testReadWriteAt (test_io.TestIOWorld) ... ok
testReadWriteAtAll (test_io.TestIOWorld) ... ok
testReadWriteAtAllBeginEnd (test_io.TestIOWorld) ... ok
testReadWriteOrdered (test_io.TestIOWorld) ... ok
testReadWriteOrderedBeginEnd (test_io.TestIOWorld) ... ok
testReadWriteShared (test_io.TestIOWorld) ... ok
testAllocate (test_memory.TestMemory) ... ok
testFromAddress (test_memory.TestMemory) ... ok
testFromBufferArrayRO (test_memory.TestMemory) ... ok
...
```
